[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.31.0"
ci = "github"
installers = ["shell", "powershell", "homebrew"]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
hosting = "github"
merge-tasks = false
allow-dirty = ["ci"]

[dist.dependencies.apt]
ffmpeg = "*"
libavcodec-dev = "*"
libavformat-dev = "*"
libavutil-dev = "*"
libswscale-dev = "*"
libswresample-dev = "*"
libavdevice-dev = "*"
libavfilter-dev = "*"
libclang-dev = "*"
pkg-config = "*"
libxkbcommon-dev = "*"
libxcb1-dev = "*"
libxcb-render0-dev = "*"
libxcb-shape0-dev = "*"
libxcb-xfixes0-dev = "*"
libdbus-1-dev = "*"
libgl-dev = "*"
libegl-dev = "*"
libwayland-dev = "*"

[dist.dependencies.brew]
ffmpeg = "*"
pkg-config = "*"
